name: Build and Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.2"
          channel: "stable"

      - name: Flutter doctor
        run: flutter doctor -v

      - name: Build Flutter app
        run: flutter build windows --release

      - name: Build updater
        run: cargo build --release
        working-directory: updater

      - name: Package app
        run: |
          mkdir windows
          copy LICENSE windows
          copy updater\target\release\updater.exe windows
          copy build\windows\x64\runner\Release\* windows

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows.zip
          path: windows/*

  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libgtk-3-dev

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.2"
          channel: "stable"

      - name: Flutter doctor
        run: flutter doctor -v

      - name: Build Flutter app
        run: flutter build linux --release

      - name: Build updater
        run: cargo build --release
        working-directory: updater

      - name: Package app
        run: |
          mkdir linux
          cp LICENSE linux
          cp updater/target/release/updater linux/
          cp -r build/linux/x64/release/bundle/* linux/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux.zip
          path: linux/*

  build-macos:
    name: Build macOS
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.2"
          channel: "stable"

      - name: Flutter doctor
        run: flutter doctor -v

      - name: Build Flutter app
        run: flutter build macos --release

      - name: Build updater
        run: cargo build --release
        working-directory: updater

      - name: Package app
        run: |
          mkdir macos
          cp LICENSE macos
          cp updater/target/release/updater macos/
          cp -r build/macos/Build/Products/Release/* macos/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos.zip
          path: macos/*
