name: Build Tauri App

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  flutter:
    name: Build Flutter Web
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.0"
          channel: "stable"

      - name: Build Flutter web
        run: |
          cd flutter
          flutter build web --release

      - name: Upload Flutter build
        uses: actions/upload-artifact@v4
        with:
          name: flutter-build-${{ matrix.os }}
          path: flutter/build/web

  updater:
    name: Build Updater
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Build updater
        run: |
          cd src-tauri/updater
          cargo build --release

      - name: Upload updater
        uses: actions/upload-artifact@v4
        with:
          name: updater-${{ matrix.os }}
          path: src-tauri/updater/target/release/*

  app:
    name: Build Tauri App
    runs-on: ${{ matrix.os }}
    needs: [flutter, updater]
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Download Flutter build
        uses: actions/download-artifact@v4
        with:
          name: flutter-build-${{ matrix.os }}
          path: flutter/build/web

      - name: Download Updater
        uses: actions/download-artifact@v4
        with:
          name: updater-${{ matrix.os }}
          path: src-tauri/updater/target/release

      - name: Install frontend deps
        run: |
          cd src-tauri
          npm install

      - name: Build Tauri app
        run: |
          cd src-tauri
          cargo build --release

      - name: Package Release Zip
        run: |
          cd src-tauri/target/release
          if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
            zip -r linux.zip launcher ../LICENSE
          elif [ "${{ matrix.os }}" = "macos-latest" ]; then
            zip -r macos.zip launcher ../LICENSE
          else
            powershell Compress-Archive -Path launcher.exe,../../LICENSE -DestinationPath windows.zip -Force
          fi

      - name: Upload final zip
        uses: actions/upload-artifact@v4
        with:
          name: release-${{ matrix.os }}
          path: src-tauri/target/release/*.zip
